[randd]
cmd = ["/sbin/randd"]

[ptyd]
cmd = ["/sbin/ptyd"]

[pcid]
cmd = ["/sbin/pcid", "/etc/pcid.toml"]

[00_base]
cmd = ["true"]
deps = ["randd", "ptyd", "pcid"]


[ethernetd]
cmd = ["/sbin/ethernetd"]

[ipd]
cmd = ["/sbin/ipd"]
deps = ["ethernetd"]

[tcpd]
cmd = ["/sbin/tcpd"]
deps = ["ipd"]

[udpd]
cmd = ["/sbin/udpd"]
deps = ["ipd"]

[dhcpd]
cmd = ["dhcpd", "-b"]
deps = ["tcpd", "udpd"]

[10_net]
cmd = ["true"]
deps = ["ethernetd", "ipd", "tcpd", "udpd", "dhcpd"]


[20_orbital]
cmd = ["/sbin/orbital", "display:3/activate", "/ui/bin/orblogin", "/ui/bin/launcher"]


[console]
cmd = ["getty", "display:2"]
deps = ["ptyd"]

[debug]
cmd = ["getty", "debug:", "-J"]
deps = ["ptyd"]

[30_console]
cmd = ["true"]
deps = ["console", "debug"]
